Tile collision updates, restored SaveData ability, reset player positions to default
aknetk/OpenMania pull request #3
Opened 2021-08-02 03:31 UTC by Axanery

2021-08-02 16:24 UTC, aknetk requested changes
Couple changes needed before The m e r g e

2021-08-02 16:24 UTC, aknetk commented on Scripts/OpenMania/Stage/Common/Ring.hsl
>                  this.X = sensor["X"] + halfW;
Might wanna fix the `sensor["X"]` and `sensor["Y"]` stuff on this line 222, 229, 236, 245, and wherever else you can Find `sensor["` just in case

2021-08-02 16:24 UTC, aknetk commented on Scripts/OpenMania/Other/TileCollisionDebugger.hsl
>                  this.DrawArrow(sensor["X"], sensor["Y"], sensor["Angle"], 8);
Same as the other comment

2021-12-13 09:14 UTC, Axanery commented
I finally fixed those sensors. I have no idea why I never bothered to fix it until just now, sorry. There shouldn't be any more instances of sensor["X"] and the like, they've been replaced.

2021-12-13 14:10 UTC, aknetk requested changes
Just a small change

2021-12-13 14:10 UTC, aknetk commented on Scripts/OpenMania/Stage/Common/Ring.hsl
> +                this.Y = this.SensorYd + halfH;
Is this a typo? the extra "d" at the end of "this.SensorYd" I mean

2021-12-13 22:16 UTC, Axanery commented
Gah, of course there was a typo. My fault.

2021-12-13 23:03 UTC, merged